### ISSUE TITLE
Spanish Flu

### ISSUE THREAD

**Issue by tleonard6** [treypujats/COVID19#20]
There's a request to overlay the plot of IHME and CHIME with the Spanish flu, something with units like cases/thousand.  If this is still open tomorrow I'll get to it then

**Comment by galarcon0308** [comment]
Can we select a different pandemic? Like Hong Kong of 1958 or 1968? The spanish flu contains a TON of uncertainty in its data. I personally haven't been able to find a reliable source for actual numbers due to the time period it occurred.  Also the Hong Kong ones tend to fit to this one a little better, once this pandemic is adjusted for unaccounted cases. Do you think they are trying to compare length? severity? For a severity I have a background paper on the past ones, with estimates for COVID. One could change the estimates easily. 

Let me know what you think.

**Comment by tleonard6** [comment]
@galarcon0308 That's a great idea.  They specifically asked for the Spanish flu, but if there's better info and it's fairly ready, then I would jump on that first.  I think they're thinking about the type of contagiousness and large spread of it across the world.  This comparison will go up the chain with other outputs.  If you have the stuff ready, feel free to send it my way.

**Comment by galarcon0308** [comment]
[COVID Pandemic Historical Comparison V4.4 (1)[2305843009218981870].docx](https://github.com/treypujats/COVID19/files/4459528/COVID.Pandemic.Historical.Comparison.V4.4.1.2305843009218981870.docx)

Let me know if this helps or if you need more. This was written back when fatality rate was thought to be 1% (note: not case rate fatality which is higher due to confirmed cases not capturing actual cases). Most places believe a 0.4% might be appropriate applied against the estimated population that get's infected (known and not known infections). Again you can readjust the number in that table if you want. The chart at the end might help with possible scenario comparison also.

**Comment by galarcon0308** [comment]
I will also say I think this paper went through A9 before? Don't know what happened to it, so hoping this isn't a repeat for you all

**Comment by tleonard6** [comment]
Thank you! I'm thinking we'll probably have to skip this effort.  There are definitely resources where people tried to estimate the time series progression of the Spanish Flu, but they don't make any of the data available.  Unless there are existing data sets available, we probably don't have the extra resources to dig into this.
