### ISSUE TITLE
Hospitalization_all_locs download

### ISSUE THREAD

**Issue by jrlindell** [treypujats/COVID19#3]
It may just be today, but since it is 4/7/2020, the app assumes the downloaded file to be 2020_4_6.1, but it is actually 2020_4_5.08

Not sure why that is

**Comment by treypujats** [comment]
Is it running or does it not let it run? Either way I’ll fix it and thanks
for bringing that to my attention

**Comment by jrlindell** [comment]
Warning in unzip(temp, files = filename) :
  requested file not found in the zip file
Warning in file(file, "rt") :
  cannot open file '2020_04_06.1/Hospitalization_all_locs.csv': No such file or directory
Error in file(file, "rt") : cannot open the connection

**Comment by treypujats** [comment]
Did you do the latest pull?
That’s an issue I’m working on. IHME data changes daily, so they upload it
to a zip file and change the name of it. In the most current code, I
believe we fixed that but we have errors occasionally with pulling the
data.

**Comment by galarcon0308** [comment]
temp <- tempfile()
download.file("https://ihmecovid19storage.blob.core.windows.net/latest/ihme-covid19.zip", temp, mode="wb")
zipdf <- unzip(temp, list = TRUE)
csv_file <- zipdf$Name[2]
IHME_Model <- read.table(unz(temp, csv_file), header = T, sep = ",")
unlink(temp)


The master code has this update since yesterday. Instead of using a name, it grabs the file and pulls it from the zip. Lemme know if this updated code is giving issues. If so, we have another idea for a fix. Thanks for reporting these!

**Comment by galarcon0308** [comment]
I'll give both these issues a couple days before closing, to ensure this issue doesn't keep cropping up

**Comment by ret394** [comment]
why are you updating so frequently?

**Comment by treypujats** [comment]
We are updating as we get tasked with new things to include in the
dashboard and bugs we fix.
