### ISSUE TITLE
Hospital utilization accuracy

### ISSUE THREAD

**Issue by ajkeith** [treypujats/COVID19#9]
Dr. Giddings: I am exploring CHAD this morning as a sort of beta tester.  Looking at the Current Local Health tab for Joint Base Andrews-Naval Air Facility shows hospital bed utilization of 110.4% but when I flip to the Local Health Projections tab even the highest value shown for the “Past Data Daily Hospitalizations” curve is significantly below the red line that’s supposed to indicate hospital bed capacity.  Can we figure out where the error is?  If there is that much uncertainty about the actual hospitalizations data, we should not provide an estimated hospital utilization value to the tenth of a percent on the Current Local Health tab.

**Comment by galarcon0308** [comment]
We had a discussion about this as a team and deciding what the best way to display this might be. On the local health tab the hospital utilization is taking into account covid cases in the past 7 days based on average hospital stay (this can be adjusted). Since most patients don't leave the same day, accounting for the percent hospitalized in previous days gives a more accurate view of bed capacity.

On the projections page, these models give daily NEW hospitalizations. Therefore it is showing when a one day spike might break the threshold. But it is not accounting for previous covid patients. I believe this is something that was lacking in previous other COVID projection models also because the red line would then not be straight. It would probably slope down a little with the increase to account for patients still in the hospital.

Still thinking of the best route to go, all advice and feedback welcome!

**Comment by ajkeith** [comment]
Maybe another view altogether that shows an estimate of the number of COVID patients in the hospital on a given day? 

Either way, probably best to round down to the 10s (50%, 60%, etc) since this is an estimate?

**Comment by galarcon0308** [comment]
Copy, I believe we were doing the CDC overall rate, but other institutions have pegged higher rates. When plan to use population age demographics next to weight the rate from the CDC table for the region. Hopefully this will give more accuracy. But yeah another view will be helpful. Like possibly switching the charts from daily hospitalizations to daily hospital load? This way it takes into account the actual burden like you are saying

**Comment by galarcon0308** [comment]
Actually I think we are going to recalculate the past data line to be a "daily hospital resource load", IHME is already based on hospital resource load, and compute proportions of the CHIME to reflect resource load as opposed to daily new hospitalizations.

**Comment by ajkeith** [comment]
From Dr. Giddings: "I believe this [hospital utilization metric] has too many flaws (I had some concerns and Col Koewler and Dr. Matyas voiced very valid concerns in the chat at yesterday’s Zoom).  I believe it should be removed from the dashboard unless/until it can be reformulated in a way that addresses or overcomes these concerns."

**Comment by ajkeith** [comment]
I'm going to close this issue as OBE for Issue https://github.com/treypujats/COVID19/issues/23. When you do add the rectangle back (and I think you should), it should still be at a lower level of precision probably 10%, 5% or 1% but definitely not 0.1% given intraday fluctuation alone.
